modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
[[mods]]
modId="silverfishmod"
version="0.6 alpha"
displayName="Silverfish Mod"
logoFile="logo.png"
credits="Gracias al aire"
authors="Carlettos"

description='''
hola
'''

[[dependencies.silverfishmod]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silverfishmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
